# Generated by Django 3.1 on 2022-03-24 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_name', models.CharField(blank=True, max_length=20)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='garagem.garagem')),
            ],
        ),
    ]
